name: outboxkit-go-poc

services:
  postgres:
    image: "postgres:17-alpine"
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "user"
      POSTGRES_PASSWORD: "pass"
    volumes:
      - ./init.pg.sql:/docker-entrypoint-initdb.d/init.sql

  lgtm:
    image: grafana/otel-lgtm
    hostname: lgtm
    container_name: lgtm
    ports:
      - "3000:3000" # ui
      - "4317:4317" # otlp gRPC
      - "4318:4318" # otlp HTTP